### ISSUE TITLE
Handle diffs in Service annotations

### ISSUE THREAD

**Issue by ThomasVitale** [kadras-io/package-for-contour#25]
Consider:

```
#! Specify which fields should be removed before diff-ing against last applied resource.
#! See more: https://carvel.dev/kapp/docs/latest/config/#diffagainstlastappliedfieldexclusionrules
diffAgainstLastAppliedFieldExclusionRules:
- path: [metadata, annotations]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Service
      namespace: #@ data.values.namespace
      name: envoy
```
